- name: Ensure web applications are deployed
  hosts: web_servers
  gather_facts: no
  serial:
    - 1
    - 100%
  max_fail_percentage: 0

  vars:
    webapp_version: v1.0

  pre_tasks:
    - name: Ensure logging the deployment start
      lineinfile:
        path: /tmp/times.txt
        create: yes
        line: "{{ lookup('pipe', 'date') }}: Deploying version {{ webapp_version }} to {{ inventory_hostname }}"
      delegate_to: localhost

  roles:
    - role: webapp

  post_tasks:
    - name: Ensure logging the deployment completion
      lineinfile:
        path: /tmp/times.txt
        create: yes
        line: "{{ lookup('pipe', 'date') }}: Deployment complete {{ webapp_version }} to {{ inventory_hostname }}"
      delegate_to: localhost
